name: Setup and Test MySQL Database
 
on: [push]
 
jobs:
  test-database:
    runs-on: ubuntu-latest
 
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shareameal
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
 
      - name: Install mocha
        run: |
          npm install -g mocha
          chmod +x "$(command -v mocha)"
 
      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install mysql-client
 
      - name: Wait for MySQL to be available
        run: |
          until mysql -h127.0.0.1 -uroot -proot -e ";" ; do sleep 1 ; done
 
      - name: Create database tables
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "USE shareameal; SOURCE share-a-meal.sql;"
 
      - name: Run tests
        run: |
          npm test